settings:
  subjects:
    Eng:
      name: Іноземна мова
      link: "https://meet.google.com/cod-ppfe-nvt"
      audience: "-"
    UkrLit:
      name: Українська література
      link: "https://meet.google.com/etk-gohy-gss"
      audience: "-"
    UkrLang:
      name: Українська мова
      link: "https://meet.google.com/had-sigv-omo"
      audience: "-"
    Hist:
      name: "Історія: Україна і світ"
      link: "https://meet.google.com/mxs-jmcd-gxq"
      audience: "-"
    PE:
      name: Фізична культура
      link: "https://meet.google.com/oec-ekrx-tjx"
      audience: "-"
    Math:
      name: Математика
      link: "-"
      audience: "-"
    Arch:
      name: Архітектура комп'ютера
      link: "https://meet.google.com/xap-wwcc-quv"
      audience: "-"
    Tech:
      name: Технології
      link: "https://meet.google.com/rrc-enzd-umn"
      audience: "-"
    Prog:
      name: Основи програмування та алгоритмічні мови
      link: "-"
      audience: "-"
    Micro:
      name: Мікропроцесорна техніка
      link: "-"
      audience: "-"
    Law:
      name: Правознавство
      link: "-"
      audience: "-"

  schedule:
    - 
      1: [ Eng, UkrLit, UkrLang, Hist ]
      2: [ null, null, PE, Math ]
      3: [ null, null, null, null ]
      4: [ Arch, Arch, Tech, Prog ]
      5: [ Micro, Prog, Math, Law ]
    - 
      1: [ null, null, null, null ]
      2: [ null, null, null, null ]
      3: [ null, null, null, null ]
      4: [ null, null, null, null ]
      5: [ null, null, null, null ]

  saturday_schedule:
    "12.09.2026":
      week: 1
      day: 1
    "19.09.2026":
      week: 1
      day: 2
    "26.09.2026":
      week: 1
      day: 3
    "03.10.2026":
      week: 1
      day: 4
    "10.10.2026":
      week: 1
      day: 5
    "17.10.2026":
      week: 2
      day: 1
    "24.10.2026":
      week: 2
      day: 2
    "31.10.2026":
      week: 2
      day: 3
    "07.11.2026":
      week: 2
      day: 4
    "14.11.2026":
      week: 2
      day: 5
    "21.11.2026":
      week: 1
      day: 1

  time:
    - "08:00 – 09:35"
    - "09:50 – 11:25"
    - "11:40 – 13:15"
    - "13:30 – 15:05"
    - "15:20 – 16:55"

  admins:
    - 6133407632
    - 814528657

  offline_days:
    - 4
    - 5

  academic_context:
    reference_date: "2026-08-31"
    reference_week: 1

  app_version: "1.6.1"
  whats_new_text: |
    Що нового <tg-emoji emoji-id='5294325496228620537'>❓</tg-emoji>
    - Прибрано показ аудиторій у непотрібні дні.
    - Збільшено швидкість реагування на повідомлення.
    - Додано сповіщення про повітряну тривогу в групу.
    - Виправлено логіку тривог.
    - Прибрано прев'ю у посилань.
    - Додано функцію "Розклад по даті" - використовувати через кнопку в головному меню або просто надіславши дату в чат у форматі РРРР.ММ.ДД, або ММ.ДД (для поточного року), або ДД (для поточного місяця).
    - Виправлено додавання інлайн-кнопок для загальних чатів.
